version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:github-actions)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:docker)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/dockerfiles/bot/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:docker)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"
