version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:github-actions)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:pip)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/db"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:dockerfile-db)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/discord"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:dockerfile-discord)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"
