services:
  discord:
    image: ghcr.io/act-kithub/kithubsys/discord:${IMAGE_TAG:-latest}
    env_file:
      - ./envs/discord.env
      - ./envs/db.env
      - ./envs/sentry.env
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
      db-migrator:
        condition: service_completed_successfully
    networks:
      - db

  db:
    image: postgres:16
    env_file:
      - ./envs/db.env
    environment:
      POSTGRES_DB: main
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U postgres -d main
      interval: 2s
      timeout: 5s
      retries: 30
    networks:
      - db

  db-migrator:
    image: ghcr.io/act-kithub/kithubsys/db-migrator:${IMAGE_TAG:-latest}
    tty: true
    env_file:
      - ./envs/db.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

volumes:
  pg_data:

networks:
  db:
    driver: bridge
