version: '3'

services:
  bot:
    build: ./dockerfiles/bot
    volumes:
      - ./bot:/opt
    networks:
      - nw_kithubsys
    env_file:
      - envs/bot.env
    restart: always

volumes:
  maria_data:

networks:
  nw_kithubsys:
    driver: bridge
