version: '3'

services:
  php:
    # image: php:8.1-apache
    build: ./dockerfiles/php
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
      - ./config/apache2:/etc/apache2
    ports:
      - "127.0.0.1:51220:80"
    networks:
      - nw_kithubsys
    restart: always
  db:
    image: mariadb:10.7.1
    volumes:
      - ./maria_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:51221:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: application
      MYSQL_PASSWORD: applicationpassword
    networks:
      - nw_kithubsys
  bot:
    build: ./dockerfiles/bot
    volumes:
      - ./bot:/opt
    networks:
      - nw_kithubsys
    restart: always

volumes:
  maria_data:

networks:
  nw_kithubsys:
    driver: bridge
