name: Check services healthy

on:
  pull_request_target:

jobs:
  check_healthy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        make envs:setup
        sed -i 's/DISCORD_BOT_TOKEN=""/DISCORD_BOT_TOKEN="${{ secrets.CIBOT_TOKEN }}"/' envs/discord.env

    - name: Build and start services
      run: make up

    - name: Wait for services to be ready and check health
      run: |
        max_retries=5
        retry_interval=5
        
        for i in $(seq 1 $max_retries)
        do
          service_status=$(make ps)
          if echo "$service_status" | grep -qiE "(starting|restarting|unhealthy)"; then
            echo "Services are still initializing or unhealthy... (Attempt $i/$max_retries)"
            echo "$service_status"
            
            if [ $i -eq $max_retries ]; then
              echo "Services did not stabilize within the allocated time."
              make logs:once
              exit 1
            fi
            
            sleep $retry_interval
          else
            echo "All services have stabilized!"
            break
          fi
        done
        
        # Final health check
        service_status=$(make ps)
        if echo "$service_status" | grep -qiE "(unhealthy|exited|dead)"; then
          echo "Some services are in an unhealthy state:"
          echo "$service_status"
          make logs:once
          exit 1
        else
          echo "All services are healthy!"
          echo "$service_status"
          make logs:once
        fi

    - name: Clean up
      run: make down