name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  require_restart:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[require_restart]')"
    steps:
    - run: echo "Require restart"
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Deploy
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USERNAME }}
           port: ${{ secrets.SSH_PORT }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd ${{ secrets.SERVER_DEPLOY_DIR }}
             git pull origin main
  restart:
    runs-on: ubuntu-latest
    needs: require_restart
    steps:
       - name: Restart
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USERNAME }}
           port: ${{ secrets.SSH_PORT }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd ${{ secrets.SERVER_DEPLOY_DIR }}
             docker-compose build --no-cache
             docker-compose up -d
